[build]
  command = "hugo --gc --minify --baseURL $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.132.2"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

